apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: namespace-egress-policy
spec:
  egress: 
  - type: Allow
    to:
      dnsName: www.google.com
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0