apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: logentryhandler
spec:
  compiledAdapter: stdio
  params:
    logStream: STDOUT
    outputAsJson: true
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: logentryrequest
spec:
  compiledTemplate: logentry
  params:
    severity: '"info"'
    timestamp: request.time | timestamp("2015-01-02T15:04:35Z")
    variables:
      source: source.labels["app"] | "unknown"
      dest_app: destination.labels["app"] | "unknown"
      dest_workload: destination.workload.name | "unknown"
      dest_service: destination.service.name | "unknown"
      host: request.host | "unknown"
      headers: request.headers | emptyStringMap()
      allow: source.labels["allow-google"] | "unknown"
      sni: connection.requested_server_name | "notsure"
    monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: logentryrule
spec:
  match: source.labels["app"] == "sleep" && destination.labels["app"] == "istio-egressgateway"
  actions:
  - handler: logentryhandler
    instances: [ logentryrequest ]